networks:
  diagrammer.net:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  front-node-modules:
  front-next:
  back-node-modules:
  back-dist:


services:

  back-diagrammer:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: build_docker/Dockerfile
    ports:
      - '3002:3001' # API NestJS
      - '3032:3032' # Hocuspocus WebSocket
    volumes:
      - ./backend:/app:delegated
      - back-node-modules:/app/node_modules
      - back-dist:/app/dist
    working_dir: /app
    networks:
      - diagrammer.net
    depends_on:
      diagrammer.db:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@diagrammer.db:5432/diagrammer?schema=public
      - NODE_ENV=${NODE_ENV:-development}
      - REDIS_HOST=redis 
      - REDIS_PORT=6379 
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true 
    command: >
      sh -c "
        echo 'Attente de la base de données...' &&
        while ! nc -z diagrammer.db 5432; do sleep 1; done &&
        echo 'Base de données prête !' &&
        
        # On installe les dépendances si nécessaire
        npm install &&
        
        echo 'Génération du client Prisma...' &&
        npx prisma generate &&
        
        echo 'Synchronisation du schéma (db push)...' &&
        npx prisma db push --accept-data-loss &&
        
        echo 'Démarrage de l application...' &&
        npm run start:dev
      "
    restart: unless-stopped

  front-diagrammer:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: build_docker/Dockerfile
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    volumes:
      - ./frontend:/app:delegated
      - front-node-modules:/app/node_modules
      - front-next:/app/.next
    working_dir: /app
    networks:
      - diagrammer.net
    depends_on:
      - back-diagrammer
    env_file:
      - .env
    environment:
      - PORT=3000
    command: >
      sh -c "
        npm install &&
        npm run dev -- -H 0.0.0.0
      "
    restart: unless-stopped

  diagrammer.db:
    image: postgres:16-alpine
    ports:
      - '15432:5432'
    networks:
      - diagrammer.net
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "16379:6379"
    networks:
      - diagrammer.net
    volumes:
      - redis-data:/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - '${ADMINER_PORT:-8080}:8080'
    networks:
      - diagrammer.net
    depends_on:
      - diagrammer.db
    restart: unless-stopped
